// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrTmBUzfLF1KUql93WR66Wd2fTAz7AqHY',
    appId: '1:78857376712:web:ff62891861e8b69098e6fd',
    messagingSenderId: '78857376712',
    projectId: 'skin-firts',
    authDomain: 'skin-firts.firebaseapp.com',
    storageBucket: 'skin-firts.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbgWazV_FUCn1H5bvUpHj3nSepLQede8k',
    appId: '1:78857376712:android:f7a93a6cf36f8f3c98e6fd',
    messagingSenderId: '78857376712',
    projectId: 'skin-firts',
    storageBucket: 'skin-firts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvPxyZ6V4_AzbxWTGutPQYrvNr41z-j9g',
    appId: '1:78857376712:ios:7c05e6357ab4d34598e6fd',
    messagingSenderId: '78857376712',
    projectId: 'skin-firts',
    storageBucket: 'skin-firts.firebasestorage.app',
    iosBundleId: 'com.example.skinFirts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvPxyZ6V4_AzbxWTGutPQYrvNr41z-j9g',
    appId: '1:78857376712:ios:7c05e6357ab4d34598e6fd',
    messagingSenderId: '78857376712',
    projectId: 'skin-firts',
    storageBucket: 'skin-firts.firebasestorage.app',
    iosBundleId: 'com.example.skinFirts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrTmBUzfLF1KUql93WR66Wd2fTAz7AqHY',
    appId: '1:78857376712:web:29a97a5bfd0d882398e6fd',
    messagingSenderId: '78857376712',
    projectId: 'skin-firts',
    authDomain: 'skin-firts.firebaseapp.com',
    storageBucket: 'skin-firts.firebasestorage.app',
  );
}
